spring:
  application:
    name: Repoo

  config:
    import:
      - optional:file:env/rtp.env[.properties]

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET_KEY}
    access:
      expiration: ${ACCESS_TIME}
    refresh:
      expiration: ${REFRESH_TIME}


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


logging:
  level:
    org:
      springframework:
        security: debug
